// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5Qa-KYGEiUOjRaHHQtdxczBz5VfzALU',
    appId: '1:370353571625:web:1670c801fe942526f4d938',
    messagingSenderId: '370353571625',
    projectId: 'chatbot-app-443a0',
    authDomain: 'chatbot-app-443a0.firebaseapp.com',
    storageBucket: 'chatbot-app-443a0.firebasestorage.app',
    measurementId: 'G-SY5NCPTZ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3UvTGuKHKsQvERTf9dSNcT0_teOsevlQ',
    appId: '1:370353571625:android:4d5c079ceec427e0f4d938',
    messagingSenderId: '370353571625',
    projectId: 'chatbot-app-443a0',
    storageBucket: 'chatbot-app-443a0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL5Qa-KYGEiUOjRaHHQtdxczBz5VfzALU',
    appId: '1:370353571625:web:80b385c2e6c18a44f4d938',
    messagingSenderId: '370353571625',
    projectId: 'chatbot-app-443a0',
    authDomain: 'chatbot-app-443a0.firebaseapp.com',
    storageBucket: 'chatbot-app-443a0.firebasestorage.app',
    measurementId: 'G-5ZK45498VG',
  );
}
